#!/usr/bin/env python3
"""Generate demo/Semi.Avalonia.Demo/Constant/IconMeta.cs from semi-design icon metadata.

The semi-design repository (https://github.com/DouyinFE/semi-design) ships a
meta.json describing every icon name and its design category
(packages/semi-icons/src/svgs/meta.json). This script maps each `SemiIcon*`
StreamGeometry resource key in src/Semi.Avalonia/Icons/*.axaml to that category
and emits a static C# lookup table used by IconDemo.

Keys that come from AIIcons.axaml are labelled "AI Icons"; keys that have no
meta entry are labelled "Other".

Usage:
    python scripts/generate-icon-meta.py <path-to-semi-design-meta.json>
"""

import json
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ICONS_DIR = os.path.join(REPO_ROOT, "src", "Semi.Avalonia", "Icons")
OUTPUT_PATH = os.path.join(REPO_ROOT, "demo", "Semi.Avalonia.Demo", "Constant", "IconMeta.cs")

AI_CATEGORY = "AI Icons"
FALLBACK_CATEGORY = "Other"


def pascal_to_snake(s: str) -> str:
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", s)
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s)
    return s.lower()


def normalize(s: str) -> str:
    """Compare names ignoring the separators meta.json is inconsistent about."""
    return re.sub(r"[^a-z0-9]", "", s.lower())


def load_meta(meta_path: str):
    with open(meta_path, encoding="utf-8") as f:
        entries = json.load(f)
    by_name = {}
    for entry in entries:
        by_name.setdefault(normalize(entry["name"]), entry["category"])
    order = []
    for entry in entries:
        if entry["category"] not in order:
            order.append(entry["category"])
    return by_name, order


def load_keys():
    """Return [(file_stem, resource_key)] in declaration order."""
    keys = []
    for file_name in sorted(os.listdir(ICONS_DIR)):
        if not file_name.endswith(".axaml"):
            continue
        with open(os.path.join(ICONS_DIR, file_name), encoding="utf-8") as f:
            keys.extend(
                (os.path.splitext(file_name)[0], m.group(1))
                for m in re.finditer(r'x:Key="(SemiIcon[^"]+)"', f.read())
            )
    return keys


def build_mapping(meta_path: str):
    meta_by_name, meta_order = load_meta(meta_path)
    categories = {}
    for stem, key in load_keys():
        if stem == "AIIcons":
            categories[key] = AI_CATEGORY
            continue
        snake = pascal_to_snake(key[len("SemiIcon"):])
        categories[key] = meta_by_name.get(normalize(snake), FALLBACK_CATEGORY)

    used = set(categories.values())
    order = [c for c in meta_order if c in used]
    order += [c for c in (AI_CATEGORY, FALLBACK_CATEGORY) if c in used]
    return categories, order


def emit(categories, order):
    lines = [
        "// <auto-generated>",
        "// Generated by scripts/generate-icon-meta.py from semi-design",
        "// packages/semi-icons/src/svgs/meta.json. Do not edit manually;",
        "// re-run the script to update.",
        "// </auto-generated>",
        "using System.Collections.Generic;",
        "",
        "namespace Semi.Avalonia.Demo.Constant;",
        "",
        "public static class IconMeta",
        "{",
        f'    public const string FallbackCategory = "{FALLBACK_CATEGORY}";',
        "",
        "    public static IReadOnlyList<string> CategoryOrder { get; } =",
        "    [",
    ]
    lines += [f'        "{c}",' for c in order]
    lines += [
        "    ];",
        "",
        "    public static IReadOnlyDictionary<string, string> Categories { get; } = new Dictionary<string, string>",
        "    {",
    ]
    lines += [f'        ["{k}"] = "{v}",' for k, v in sorted(categories.items())]
    lines += [
        "    };",
        "}",
        "",
    ]
    with open(OUTPUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    meta_path = sys.argv[1]
    if not os.path.isfile(meta_path):
        sys.exit(f"meta.json not found: {meta_path}")
    categories, order = build_mapping(meta_path)
    emit(categories, order)
    unmapped = [k for k, v in categories.items() if v == FALLBACK_CATEGORY]
    print(f"wrote {OUTPUT_PATH}")
    print(f"keys: {len(categories)}, categories: {len(order)}, fallback: {unmapped}")


if __name__ == "__main__":
    main()
